Add a way to search for icons
yewprint/yewprint pull request #150
Opened 2022-09-21 15:48 UTC by yozhgoor

2022-11-07 16:17 UTC, cecton commented on build.rs
> +    src.push_str("vec![\n");
You basically have a constant here so you can use `&[]` instead of `vec![]`

2022-11-07 16:17 UTC, cecton commented on src/icon.rs
> +            if format!("{:?}", x).to_lowercase() == s.to_lowercase() {
`s` is lowercased twice

2022-11-08 03:21 UTC, cecton commented on build.rs
> +    src.push_str("vec![\n");
Good, looks better! You've converted the `vec![]` which is a dynamically sized array in heap to a fixed size array (in stack).

Next improvement: what if I told you... you don't need to return an iterator, you can return the array itself? An array is always iterable:

```rust
fn main() {
    let stuff = [1, 2, 3];
    for x in stuff {
        println!("{x:?}");
    }
}
```

2022-11-08 15:50 UTC, cecton requested changes

2022-11-08 15:50 UTC, cecton commented on src/icon.rs
> +}
I don't think we want this in the public API of yewprint. Can you move it to yewprint-doc?

You also want to us Lazy to avoid allocating at every iteration like that

2022-11-08 15:50 UTC, cecton commented on yewprint-doc/Cargo.toml
> +yew-router = "0.16"
I don't know why there was commented dependencies... not useful

```suggestion
yew = "0.19"
yew-router = "0.16"
```

2022-11-08 15:50 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +                name.to_lowercase()
You can lowercase in the lazy to avoid extra work

2022-11-08 15:50 UTC, cecton commented on yewprint-doc/src/lib.rs
> +                let branch = "HEAD";
Why this change?

2022-11-08 19:53 UTC, yozhgoor commented on src/icon.rs
> +}
I can move that in the example but I need to find a way to get the icon without adding too much noise to the example's source then

2022-11-09 07:39 UTC, cecton commented on yewprint-doc/src/lib.rs
> +                let branch = "HEAD";
But then the deployed preview does not use the correct URL to get to the sources?

2022-11-09 07:40 UTC, cecton commented on src/icon.rs
> +}
You can use modules to hide away the components that are not meant for the example

2022-11-09 07:41 UTC, cecton commented on src/icon.rs
> +}
Or you can import from `super` and put it there

2022-11-09 08:07 UTC, yozhgoor commented on yewprint-doc/src/lib.rs
> +                let branch = "HEAD";
It's because we tends to use a fork, so the branch is not on this repository but on the fork.
For this PR, the correct URL would be https://github.com/yozhgoor/yewprint/blob/icon-search/src/icon.rs
Instead of https://github.com/yewprint/yewprint/blob/icon-search/src/icon.rs

2022-11-09 08:50 UTC, yozhgoor commented on yewprint-doc/src/icon/mod.rs
> +                name.to_lowercase()
I reverted, so I can still use the CamelCase name of the Icon directly in the icon list

2022-11-09 10:29 UTC, cecton commented on yewprint-doc/src/lib.rs
> +                let branch = "HEAD";
Maybe we can also retrieve the repository somehow? The tests are executed by the worker so it probably knows the correct url

2022-11-09 21:40 UTC, yozhgoor commented on yewprint-doc/src/lib.rs
> +                let branch = "HEAD";
Hmm, doesn't fail with the CI but locally

2022-11-09 21:56 UTC, yozhgoor commented on yewprint-doc/src/lib.rs
> +                let branch = "HEAD";
So I was wrong, but if we keep `HEAD`, it doesn't fail locally nor with the CI :thinking:

2022-11-09 22:03 UTC, yozhgoor commented on src/icon.rs
> +}
Deleted and example improved :rocket:

2022-11-15 11:27 UTC, cecton commented on yewprint-doc/src/lib.rs
> +                let branch = "HEAD";
Ok so let's keep it that way for now but we should fix this in a separate PR

2022-11-15 11:30 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +                name.to_lowercase()
you can use the debug formatting on icon there instead

2022-11-15 11:36 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +                        round={true}
You don't need the `{}` for literals
```suggestion
                        large=true
                        fill=true
                        round=true
```

2022-11-15 11:36 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +            res = *icon;
You can return early to make the heuristic faster

2022-11-15 11:36 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +                                }
You can avoid a bit of duplicated code here using a variable of type `Option<IconName>` and then unwrap it using `unwrap_or(IconName::Blank)`. You can also use the `and_then` to chain the options.

2022-11-15 11:36 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +                            value={format!("{:?}", ctx.props().example_props.icon_name.clone())}
```suggestion
                            value={format!("{:?}", ctx.props().example_props.icon_name)}
```

2022-11-15 11:36 UTC, cecton commented on src/icon.rs
> -
I would keep that one... why not?

2022-11-15 12:11 UTC, yozhgoor commented on src/icon.rs
> -
I deleted it so we don't "force" that default on the public API, but I can revert that without concerns for me tho

2022-11-15 14:58 UTC, cecton commented on src/icon.rs
> -
Looks like a reasonable default to me

2022-11-15 15:07 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +                name.contains(&self.search_icon.to_lowercase())
You really need to move the `to_lowercase()` out of the loop because you are allocating at every iteration!

2022-11-15 15:07 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +                    .then_some(html! {
Using then_some here is no good because you are creating the `Html` even if the condition failed. Use closures (check `then`)

2022-11-15 15:07 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +                    source={source}
```suggestion
                    {source}
```

2022-11-15 15:07 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +                                    }
Poor indentation

2022-11-15 15:09 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +        if name == icon_name.to_lowercase() {
Wrong place to put the to_lowercase

...also, pleave move it outside the loop

2022-11-15 15:09 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +fn get_icon_from_name(name: &str) -> IconName {
Return `Option<IconName>` instead

2022-11-16 11:00 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +                                    icon_name: icon.unwrap_or_default(),
Try to keep consistency in the name of the variables. This one is icon_name and not icon

2022-11-16 16:10 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +            .step_by(1)
that's noop
```suggestion
```

2022-11-20 15:43 UTC, cecton approved these changes
All good :+1: 

You do what you want with `get_icons_from_name()`. This is what I had in mind, it's not required to merge.

2022-11-20 15:43 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +            .collect::<Vec<_>>();
Indendation 101
```suggestion
                .map(|x| (x, (x % 20 == 0).then(|| format!("{}", x).into())))
                .collect::<Vec<_>>();
```

2022-11-20 15:43 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +                        <Example ..example_props />
```suggestion
                    <Example ..example_props />
```

2022-11-20 15:43 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +            .map(|x| {
let's see what happens if you get rid of this useless function
```suggestion
        let search_string = self.search_string.to_lowercase();
        let icon_list = ICON_LIST
            .iter()
            .filter_map(|(icon_name, icon)| icon_name.contains(&search_string).then_some(*icon))
            .map(|x| {
```

2022-11-20 15:43 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +                                    .and_then(|x| get_icons_from_name(x).next());
```suggestion
                                let icon_name_string = e.target_dyn_into::<HtmlInputElement>()
                                    .map(|x| x.value().to_lowercase());
                                let icon_name = ICON_LIST
                                    .iter()
                                    .find_map(move |(icon_name, icon)| (Some(icon_name) == name.as_deref()).then_some(*icon))
                                    .unwrap_or_default();
```

2022-11-22 07:04 UTC, cecton approved these changes

2022-11-22 11:45 UTC, yozhgoor commented
I replaced the `iconSvgPaths.js` file from the one in #152 (thanks to @fstephany for the update)

2022-11-22 12:06 UTC, merged