Update dependencies
yewprint/yewprint pull request #154
Opened 2022-11-29 21:48 UTC by yozhgoor

Closes #153

2022-11-30 11:23 UTC, cecton commented
The development server is broken on my side. It doesn't rebuild after I change a file. Does it work for you??

2022-12-06 09:05 UTC, cecton commented
@yozhgoor I released implicit-clone 0.3.3 which has support for tuples. Can you check if this work better for HtmlSelect?

2022-12-08 14:02 UTC, yozhgoor commented
Needs this [PR](https://github.com/yewstack/implicit-clone/pull/14) to be merged for the `Slider<()>` example

2022-12-08 14:26 UTC, cecton requested changes

2022-12-08 14:26 UTC, cecton commented on src/tabs.rs
> +    pub id: AttrValue,
Use this:

```
diff --git a/src/tabs.rs b/src/tabs.rs
index 99755590..60ca7e46 100644
--- a/src/tabs.rs
+++ b/src/tabs.rs
@@ -3,15 +3,17 @@ use std::hash::{Hash, Hasher};
 use std::marker::PhantomData;
 use web_sys::HtmlElement;
 use yew::prelude::*;
+use implicit_clone::unsync::IArray;
+use implicit_clone::ImplicitClone;
 
-pub struct Tabs<T: Clone + PartialEq + Hash + 'static> {
+pub struct Tabs<T: ImplicitClone + PartialEq + Hash + 'static> {
     tab_refs: HashMap<u64, NodeRef>,
     indicator_ref: NodeRef,
     phantom: PhantomData<T>,
 }
 
 #[derive(Clone, PartialEq, Properties)]
-pub struct TabsProps<T: Clone + PartialEq> {
+pub struct TabsProps<T: ImplicitClone + PartialEq + 'static> {
     #[prop_or_default]
     pub animate: bool,
     #[prop_or_default]
@@ -28,10 +30,10 @@ pub struct TabsProps<T: Clone + PartialEq> {
     pub onchange: Callback<T>,
     #[prop_or_default]
     pub class: Classes,
-    pub tabs: Vec<Tab<T>>,
+    pub tabs: IArray<Tab<T>>,
 }
 
-impl<T: Clone + PartialEq + Hash + 'static> Component for Tabs<T> {
+impl<T: ImplicitClone + PartialEq + Hash + 'static> Component for Tabs<T> {
     type Message = ();
     type Properties = TabsProps<T>;
 
@@ -194,3 +196,5 @@ pub struct Tab<T> {
     pub title_class: Classes,
     pub panel_class: Classes,
 }
+
+impl<T: ImplicitClone> ImplicitClone for Tab<T> {}
```

2022-12-08 14:26 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +                                    icon={x}
```suggestion
                                    {icon}
```

2022-12-08 14:26 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +    SearchIcon(AttrValue),
Completely unneeded use of AttrValue!

Use it in props

2022-12-08 14:26 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +    search_string: AttrValue,
Unneeded

2022-12-08 14:26 UTC, cecton commented on yewprint-doc/src/icon/mod.rs
> +                                IString::from(format!("{}", ctx.props().example_props.icon_size))
Already converted for you. That's the whole point of using AttrValue in props
```suggestion
                                format!("{}", ctx.props().example_props.icon_size)
```

2022-12-08 14:26 UTC, cecton commented on yewprint-doc/src/input_group/example.rs
>  }
use it only in props

2022-12-08 14:26 UTC, cecton commented on yewprint-doc/src/progress_bar/mod.rs
> +                            ]))}
using collect() will be easier

2022-12-08 14:26 UTC, cecton commented on yewprint-doc/src/slider/example.rs
> +                        values={IArray::<(f64, Option<IString>)>::Rc(Rc::new([
Try to collect instead

2022-12-08 14:26 UTC, cecton commented on yewprint-doc/src/slider/example.rs
> +                    values={IArray::<(LogLevel, Option<IString>)>::Rc(Rc::new([
Collect

2022-12-08 14:26 UTC, cecton commented on yewprint-doc/src/slider/example.rs
> +                    value_label={IString::from(format!("{}%", self.integer))}
Already converted for you. That's the whole point of AttrValue

```suggestion
                    value_label={format!("{}%", self.integer)}
```

2022-12-08 14:26 UTC, cecton commented on yewprint-doc/src/slider/example.rs
> +                    values={IArray::<((), Option<IString>)>::Rc(Rc::new([
Collect

2022-12-08 14:26 UTC, cecton commented on yewprint-doc/src/slider/mod.rs
> +                    options={IArray::<(Option<Intent>, AttrValue)>::Rc(Rc::new([
Collect

2022-12-08 14:26 UTC, cecton commented on yewprint-doc/src/spinner/mod.rs
> +                        options={IArray::<(Option<Intent>, AttrValue)>::Rc(Rc::new([
Collect

2022-12-08 14:26 UTC, cecton commented on yewprint-doc/src/spinner/mod.rs
> +                        values={IArray::<(u32, Option<IString>)>::Rc(Rc::new([
Collect

2022-12-08 14:26 UTC, cecton commented on yewprint-doc/src/tag/example.rs
> +    tags: Vec<AttrValue>,
Use only in props

2022-12-08 14:26 UTC, cecton commented on yewprint-doc/src/tag/example.rs
> +    pub initial_tags: Vec<AttrValue>,
Use IArray (because it's props)

2022-12-08 14:26 UTC, cecton commented on yewprint-doc/src/tag/mod.rs
> +                                options={IArray::<(Option<Intent>, AttrValue)>::Rc(Rc::new([
collect

2022-12-08 14:26 UTC, cecton commented on yewprint-doc/src/text_area/mod.rs
> +                        options={IArray::<(Option<Intent>, AttrValue)>::Rc(Rc::new([
collect

2022-12-09 15:06 UTC, cecton commented on yewprint-doc/src/radio/example.rs
> +                        options={IArray::<(Lunch, AttrValue)>::Rc(Arc::new([
You need to use implicit-clone unsync btw

```
[0] [15:04:50] ~/r/yew cecton-make-callback-eq-use-context > rg 'AttrValue ='
packages/yew/src/virtual_dom/mod.rs
50:pub type AttrValue = implicit_clone::unsync::IString;
```

We don't need the sync version of the types in implicit-clone because this is all single threaded.

2022-12-12 07:20 UTC, cecton commented on src/radio.rs
> +                onchange={props.onchange.clone()}
This should have worked but it doesn't for some reason... it needs to be investigated but it's an issue in Yew:

```
error[E0277]: expected a `Fn<(yew::Event,)>` closure, found `Option<yew::Callback<yew::Event>>`
   --> src/radio.rs:37:27
    |
25  | /     html! {
26  | |         <label
27  | |             class={classes!(
28  | |                 "bp3-control",
...   |
37  | |                 onchange={&props.onchange}
    | |                           ^^^^^^^^^^^^^^^ expected an `Fn<(yew::Event,)>` closure, found `Option<yew::Callback<yew::Event>>`
...   |
50  | |         </label>
51  | |     }
    | |_____- required by a bound introduced by this call
    |
    = help: the trait `Fn<(yew::Event,)>` is not implemented for `Option<yew::Callback<yew::Event>>`
    = note: required for `&Option<yew::Callback<yew::Event>>` to implement `FnOnce<(yew::Event,)>`
    = note: required for `&Option<yew::Callback<yew::Event>>` to implement `IntoEventCallback<yew::Event>`
```

2022-12-13 17:47 UTC, cecton commented on Cargo.toml
> +implicit-clone = { git = "ssh://git@github.com/yewstack/implicit-clone.git" }
Reminder: remove before merge :warning:

2022-12-13 17:50 UTC, cecton commented on src/buttons.rs
> +                    })
Could be improved by https://github.com/yewstack/yew/pull/3039

2022-12-13 17:50 UTC, cecton commented on src/callout.rs
> +                class.clone(),
Will be improved by https://github.com/yewstack/yew/pull/3038

2022-12-13 17:53 UTC, cecton commented on src/checkbox.rs
> +) -> Html {
It is best to unpack all the props in one go. This detects unused/unimplemented props.

2022-12-13 18:08 UTC, cecton commented on yewprint-doc/src/html_select/example.rs
> +                    ].into_iter().collect::<IArray<_>>()}
Can be improved by https://github.com/yewstack/implicit-clone/pull/15

2022-12-13 18:25 UTC, cecton commented on yewprint-doc/src/tag/mod.rs
> +                                ])}
This could be improved to:

```
iarray![
    (None, istr!("None")),
    (Some(Intent::Primary), istr!("Primary")),
    (Some(Intent::Success), istr!("Success")),
    (Some(Intent::Warning), istr!("Warning")),
    (Some(Intent::Danger), istr!("Danger")),
]
```

With PR https://github.com/yewstack/implicit-clone/pull/15

2022-12-14 08:36 UTC, cecton approved these changes

2022-12-14 09:26 UTC, merged