Numeric input
yewprint/yewprint pull request #67
Opened 2020-11-03 14:45 UTC by Yozhgoor

Begin to work on the numeric input

doc: https://blueprintjs.com/docs/#core/components/numeric-input
code: https://github.com/palantir/blueprint/blob/develop/packages/core/src/components/forms/numericInput.tsx

2020-11-05 16:35 UTC, Yozhgoor commented
need some improvements and implementation of other component like ControlGroup and InputGroup

2020-12-03 21:10 UTC, Yozhgoor commented
With #68 inputGroup and controlGroup is now implemented, let's go

2021-01-05 17:29 UTC, yozhgoor commented
@cecton Maybe already push this ?
The numericInput look like a NumericInput but props not working as expected and it's not numeric at all but i will to take a look to some other component for now

2021-01-06 15:59 UTC, cecton requested changes
In the end I don't see much reason to merge early. Do you need it for something else? Otherwise it can stay as an open PR, it's okay

2021-01-06 15:59 UTC, cecton commented on yewprint-doc/src/numeric_input/mod.rs
> +                            props=example_props.clone()
```suggestion
                                callback={self.callback.clone()}
                                props=example_props.clone()
```

2021-01-06 15:59 UTC, cecton commented on yewprint/src/numeric_input.rs
> +use yew::prelude::*;
```suggestion
use crate::{Button, ButtonGroup, ControlGroup, IconName, InputGroup, Intent};
use yew::prelude::*;
```

2021-01-06 15:59 UTC, cecton commented on yewprint/src/numeric_input.rs
> +    pub class: String,
Not used.

Is this the issue you had the other day?

2021-01-06 15:59 UTC, cecton commented on yewprint/src/numeric_input.rs
> +                class="bp3-numeric-input"
```suggestion
                class=format!("bp3-numeric-input {}", self.class)
```

(Good enough until Yew 0.18 is released)

2021-01-09 15:07 UTC, yozhgoor commented
Thanks for the review, i take a look now

2021-01-09 15:51 UTC, yozhgoor commented
Numeric Input look like an example for now, i try to give him a less redundant and basic render.

But for now, props works! just need to begin the journey of a more functionnal NumericInput

2021-10-05 16:46 UTC, cecton commented on yewprint/src/numeric_input.rs
> +                        self.props.value = Some(self.props.max_value.clone());
This is strange. Props are something you get from the parent component but you are not supposed to modify them. In this particular case you do change them and manipulate them like it is part of your state... which is strangely "right" because the props are a field in the state in Yew.

Ok so this works and makes sense but you wouldn't be able to do that in React for example. It would be nice to have other's opinion on this.

2021-10-05 16:46 UTC, cecton commented on yewprint/src/numeric_input.rs
> +            self.props = props;
You need to check for a change in `value`. Because the parent component CAN change the value for you and you will need to update the inputgroup accordingly.

2021-10-05 16:46 UTC, cecton commented on yewprint/src/numeric_input.rs
> +                    true
I'm not sure if there should be a valid action to do when your props' value is None...

Putting the minimum seems wrong. Probably using 0 would be better. But then again you don't know if 0 is in the range. Probably the best thing to do here is to do nothing at all.

(Same story in Msg::Up)

```suggestion
                    false
```

2021-10-05 16:46 UTC, cecton commented on yewprint/src/numeric_input.rs
> +                    false
~~You still need to update `input` otherwise I think you can't write a number starting by `-`.~~

This wouldn't work with React. You can keep it that way I guess

2021-10-05 16:46 UTC, cecton commented on yewprint/src/numeric_input.rs
> +            }
dead code

2021-10-05 16:46 UTC, cecton commented on yewprint-doc/src/numeric_input/example.rs
> +                min_value=0
```suggestion
                min_value=-10
```

2021-10-06 12:58 UTC, merged